// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmVyu3lGVHGMNcG_cr-ZoxKAufwSAJqM',
    appId: '1:957554861383:web:2f92284cf784382ad71862',
    messagingSenderId: '957554861383',
    projectId: 'sensibuddy1',
    authDomain: 'sensibuddy1.firebaseapp.com',
    databaseURL: 'https://sensibuddy1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensibuddy1.firebasestorage.app',
    measurementId: 'G-LPC1MSFKQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJoYSc4fnw6gAqtRuBUvGpxrBSY73drc',
    appId: '1:957554861383:android:e3cd0e367e117c83d71862',
    messagingSenderId: '957554861383',
    projectId: 'sensibuddy1',
    databaseURL: 'https://sensibuddy1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensibuddy1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLkHSEHMJUL20RLDa84LE-DN-1tZRYDA',
    appId: '1:957554861383:ios:6feafb8d464f1d3ed71862',
    messagingSenderId: '957554861383',
    projectId: 'sensibuddy1',
    databaseURL: 'https://sensibuddy1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensibuddy1.firebasestorage.app',
    iosBundleId: 'com.example.sensibuddy1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmLkHSEHMJUL20RLDa84LE-DN-1tZRYDA',
    appId: '1:957554861383:ios:6feafb8d464f1d3ed71862',
    messagingSenderId: '957554861383',
    projectId: 'sensibuddy1',
    databaseURL: 'https://sensibuddy1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensibuddy1.firebasestorage.app',
    iosBundleId: 'com.example.sensibuddy1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmVyu3lGVHGMNcG_cr-ZoxKAufwSAJqM',
    appId: '1:957554861383:web:3bcbf7b3cf67a930d71862',
    messagingSenderId: '957554861383',
    projectId: 'sensibuddy1',
    authDomain: 'sensibuddy1.firebaseapp.com',
    databaseURL: 'https://sensibuddy1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensibuddy1.firebasestorage.app',
    measurementId: 'G-24549XD1T7',
  );
}
